name: Pontificaal
favicon: null
layout_spectrum: 0.76288
typography_spectrum: 0.24208
title: Pontificaal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feca01'
    - '#09a0dc'
    - '#e05312'
    - '#a0176d'
    - '#547e5a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
