typography_spectrum: 0.18122
color:
  brandColors:
    - '#ffffff'
    - '#fed530'
    - '#ae106c'
    - '#e65a22'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.96534
analytics:
  google: null
  facebook: null
  twitter: null
name: Pontificaal
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Pontificaal
description: Creatieve marketing & communicatie met lef
purpose: []
